#!/bin/bash
set -euo pipefail

MY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIST_FILE="${MY_DIR}/proprietary-files.txt"
BLOBS_MK="${MY_DIR}/vendor-blobs.mk"

if [[ ! -f "${LIST_FILE}" ]]; then
	echo "Missing list: ${LIST_FILE}"
	exit 1
fi

{
	echo "# Auto-generated by setup-makefiles.sh"
	echo "PRODUCT_COPY_FILES += \\" 
	while IFS= read -r raw_line || [[ -n "${raw_line}" ]]; do
		line="${raw_line%%#*}"
		line="${line%%;*}"
		line="$(echo "${line}" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
		[[ -z "${line}" ]] && continue

		if [[ "${line}" == *":"* ]]; then
			src_rel="${line%%:*}"
			dst_rel="${line##*:}"
		else
			src_rel="${line}"
			dst_rel="${line}"
		fi

		[[ "${src_rel}" == vendor/* ]] || continue
		[[ "${dst_rel}" == vendor/* ]] || continue

		src_path="vendor/infinix/X663/proprietary/${src_rel}"
		dst_path="\$(TARGET_COPY_OUT_VENDOR)/${dst_rel#vendor/}"
		echo "    ${src_path}:${dst_path} \\" 
	done < "${LIST_FILE}"
} > "${BLOBS_MK}"

echo "Generated ${BLOBS_MK}"
